# Student Final Score Prediction Project
## The goal of this project is to build a machine-learning model that predicts a student's final score based on their study behavior and previous academic performance.

In [10]:
import pandas as pd
df = pd.read_csv("student_final_score_project.csv")
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [11]:
df.isnull().sum()

student_id              0
study_hours            24
attendance             20
homework_score         22
previous_test_score    18
tutoring_sessions       0
sleep_hours            16
final_score             0
dtype: int64

In [12]:
copy_df=df.copy()
copy_df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [13]:
copy_df["study_hours"] = copy_df["study_hours"].fillna(copy_df["study_hours"].mean())
copy_df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [8]:
copy_df.isnull().sum()

student_id              0
study_hours             0
attendance             20
homework_score         22
previous_test_score    18
tutoring_sessions       0
sleep_hours            16
final_score             0
dtype: int64

In [14]:
copy_df["attendance"] = copy_df["attendance"].fillna(copy_df["attendance"].mean())
copy_df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [15]:
copy_df.isnull().sum()

student_id              0
study_hours             0
attendance              0
homework_score         22
previous_test_score    18
tutoring_sessions       0
sleep_hours            16
final_score             0
dtype: int64

In [16]:
copy_df["homework_score"] = copy_df["homework_score"].fillna(copy_df["homework_score"].mean())
copy_df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [17]:
copy_df.isnull().sum()

student_id              0
study_hours             0
attendance              0
homework_score          0
previous_test_score    18
tutoring_sessions       0
sleep_hours            16
final_score             0
dtype: int64

In [18]:
copy_df["previous_test_score"] = copy_df["previous_test_score"].fillna(copy_df["previous_test_score"].mean())
copy_df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [16]:
copy_df.isnull().sum()

student_id              0
study_hours             0
attendance              0
homework_score          0
previous_test_score     0
tutoring_sessions       0
sleep_hours            16
final_score             0
dtype: int64

In [19]:
copy_df["sleep_hours"] = copy_df["sleep_hours"].fillna(copy_df["sleep_hours"].mean())
copy_df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [20]:
copy_df.shape

(500, 8)

In [21]:
X = copy_df[[
        "study_hours",
        "attendance",
        "homework_score",
        "previous_test_score",
        "tutoring_sessions",
        "sleep_hours"
    ]]
y = copy_df["final_score"]

# X is features/clues, while y is answer/target

# Training data - data the model is going to study
# Testing data - data the model is not going to study

In [22]:
X.head()

,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours
0,1.4,77.6,70.7,86.6,0,8.5
1,3.7,80.8,90.5,81.6,3,7.9
2,4.9,65.8,76.9,41.6,0,6.5
3,5.6,64.5,55.1,93.8,2,8.1
4,8.0,78.1,44.6,55.4,4,6.9

In [23]:
y.head()

0    79.4
1    84.2
2    72.5
3    79.3
4    83.9
Name: final_score, dtype: float64

In [2]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
)

# X_train = clues the model studies
# y_train = answers from those clues
# X_test= new clues the model has not studied
# y_test= answers from those clues

In [41]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(400, 6)
(400,)
(100, 6)
(100,)

# An algorithm is a method/rule that a model uses to learn a pattern.
# For this project, we will be using regression because final_score is a number.

In [42]:
from sklearn.linear_model import LinearRegression

# Let's create a model.

In [43]:
model = LinearRegression()

# Let's train the model.

In [44]:
model.fit(X_train, y_train)

LinearRegression()

# Let model take its exam

In [45]:
predictions = model.predict(X_test)
predictions

array([ 76.95098748,  74.17739547,  61.303976  ,  80.80552188,
        66.46973983,  75.35481682,  58.65012785,  89.69053997,
        73.43656962,  91.01236817,  72.22114669,  87.88488981,
        74.67358085,  76.32784195,  82.34723345,  69.94679371,
       101.1201049 ,  74.08643862,  96.74191588,  74.63295167,
        83.10032122,  92.47168246,  86.49363236,  77.31714953,
        72.92688105,  69.61773703,  92.48125963,  83.98439953,
        79.906173  ,  82.89977027,  73.35519735,  77.54717682,
        81.36163948,  60.71467348,  70.00877641,  85.32234445,
        60.82958604,  76.55033277,  82.62002344,  69.48078989,
        75.54056848,  65.04146374,  69.68407485,  87.79395678,
        76.39705881,  82.40032702,  73.82587249,  88.69237263,
        71.34388831,  78.54793423,  74.71498517,  87.8733559 ,
        75.4572285 ,  68.5428281 ,  63.82675378,  79.23217971,
        62.23921035,  89.02878655,  55.75901856,  65.01031009,
        71.52107918,  67.11356756,  78.2375643 ,  86.27954623,
        73.44416669,  83.34690315,  74.73087129,  70.02199534,
        97.25020258,  75.86621303,  66.97861298,  90.68207213,
        98.83084139,  73.65382687,  91.08518856,  61.41597212,
        81.56065268,  78.88046488,  76.37873887,  72.21476195,
        84.64073301,  79.61953265,  81.91409599,  79.72537247,
        81.49651155,  66.73556174,  80.59978182,  87.95745365,
        72.55708242,  86.19355823,  66.57776651,  78.12756524,
        77.85666339,  79.30633798,  77.9456327 ,  71.9388683 ,
        69.27639821,  67.49311422,  69.12567219,  73.73098288])

In [51]:
results = pd.DataFrame({
    "actual_score": y_test.values,
    "predicted_score": predictions
}
)
results

    actual_score  predicted_score
0           83.4        76.950987
1           74.0        74.177395
2           62.2        61.303976
3           82.1        80.805522
4           60.2        66.469740
..           ...              ...
95          73.4        71.938868
96          67.4        69.276398
97          68.5        67.493114
98          64.3        69.125672
99          61.6        73.730983

[100 rows x 2 columns]

# The model has learnt a useful pattern but still makes mistakes on some students

# Evaluate the model

## Because this is regression, we won't be using  accuracy, precision, and recall like we did for pass/fail category
## We are dealing with number so we use either MAE(Mean Absolute Error) or R-squared

In [54]:
from sklearn.metrics import mean_absolute_error, r2_score

In [59]:
mae = mean_absolute_error(y_test, predictions)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 4.071593328571776

# On average, the model's predictions were about 4.1 score points aways from the real scores

In [60]:
r2= r2_score(y_test, predictions)
print("R-squared:", r2)

R-squared: 0.726627151698034

# The result from r-squared is a closer fit because the rules are:
# Close to 1 - stronger fit
# Close to 0 - weak explanatory power