## CLEANING A MESSY STUDENT DATASET TO PREPARE IT FOR MACHINE LEARNING

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "student": ["A", "B", "C", "D", "E", "F"],
    "study_hours": [2, 4, np.nan, 5, 6, 8],
    "attendance": [70, np.nan, 82, 90, 95, 88],
    "subject": ["Maths", "English", "Maths", np.nan, "Maths", "English"],
    "score": [50, 65, 72, np.nan, 88, 91]
}
df=pd.DataFrame(data)
df

  student  study_hours  attendance  subject  score
0       A          2.0        70.0    Maths   50.0
1       B          4.0         NaN  English   65.0
2       C          NaN        82.0    Maths   72.0
3       D          5.0        90.0      NaN    NaN
4       E          6.0        95.0    Maths   88.0
5       F          8.0        88.0  English   91.0

In [3]:
clean_df = df.copy()
clean_df

  student  study_hours  attendance  subject  score
0       A          2.0        70.0    Maths   50.0
1       B          4.0         NaN  English   65.0
2       C          NaN        82.0    Maths   72.0
3       D          5.0        90.0      NaN    NaN
4       E          6.0        95.0    Maths   88.0
5       F          8.0        88.0  English   91.0

In [5]:
clean_df["study_hours"]= clean_df["study_hours"].fillna(clean_df["study_hours"].mean())
clean_df

  student  study_hours  attendance  subject  score
0       A          2.0        70.0    Maths   50.0
1       B          4.0         NaN  English   65.0
2       C          5.0        82.0    Maths   72.0
3       D          5.0        90.0      NaN    NaN
4       E          6.0        95.0    Maths   88.0
5       F          8.0        88.0  English   91.0

In [7]:
clean_df["attendance"]=clean_df["attendance"].fillna(clean_df["attendance"].mean())
clean_df

  student  study_hours  attendance  subject  score
0       A          2.0        70.0    Maths   50.0
1       B          4.0        85.0  English   65.0
2       C          5.0        82.0    Maths   72.0
3       D          5.0        90.0      NaN    NaN
4       E          6.0        95.0    Maths   88.0
5       F          8.0        88.0  English   91.0

In [9]:
clean_df["subject"]=clean_df["subject"].fillna(clean_df["subject"].mode()[0])
clean_df

  student  study_hours  attendance  subject  score
0       A          2.0        70.0    Maths   50.0
1       B          4.0        85.0  English   65.0
2       C          5.0        82.0    Maths   72.0
3       D          5.0        90.0    Maths    NaN
4       E          6.0        95.0    Maths   88.0
5       F          8.0        88.0  English   91.0

In [12]:
clean_df["score"]=clean_df["score"].fillna(clean_df["score"].median())
clean_df

  student  study_hours  attendance  subject  score
0       A          2.0        70.0    Maths   50.0
1       B          4.0        85.0  English   65.0
2       C          5.0        82.0    Maths   72.0
3       D          5.0        90.0    Maths   73.2
4       E          6.0        95.0    Maths   88.0
5       F          8.0        88.0  English   91.0

In [13]:
clean_df.isnull().sum()

student        0
study_hours    0
attendance     0
subject        0
score          0
dtype: int64