In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\TAIWO\Downloads\student_classes.csv")

In [3]:
df

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [5]:
df['Subject'] #selecting one column

0         Mathematics
1         Mathematics
2             Science
3             English
4         Mathematics
5    Computer Science
6         Mathematics
7     English Writing
Name: Subject, dtype: str

In [9]:
df[df['Subject']== 'Mathematics'] #filtering Mathematics subject

  Student      Subject Class_Day Class_Time  Duration_Minutes  Fee_GBP
0   Amira  Mathematics    Monday    4:00 PM                60       20
1  Taslim  Mathematics   Tuesday    6:00 PM                60       22
4   Jason  Mathematics  Saturday    2:00 PM                45       19
6   Karis  Mathematics    Sunday    3:00 PM                60       20

In [12]:
df[['Subject','Student']]

            Subject  Student
0       Mathematics    Amira
1       Mathematics   Taslim
2           Science     Ines
3           English  Ainsley
4       Mathematics    Jason
5  Computer Science  Giselle
6       Mathematics    Karis
7   English Writing   Damien

In [14]:
df[df['Fee_GBP']<=20]

   Student          Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira      Mathematics     Monday    4:00 PM                60       20
2     Ines          Science     Friday   12:00 PM                45       18
3  Ainsley          English  Wednesday   10:00 AM                60       20
4    Jason      Mathematics   Saturday    2:00 PM                45       19
6    Karis      Mathematics     Sunday    3:00 PM                60       20
7   Damien  English Writing    Tuesday   11:00 AM                60       18

In [17]:
df.sort_values('Fee_GBP', ascending = False)

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
0    Amira       Mathematics     Monday    4:00 PM                60       20
6    Karis       Mathematics     Sunday    3:00 PM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
2     Ines           Science     Friday   12:00 PM                45       18
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [18]:
df['Subject'].value_counts()

Subject
Mathematics         4
Science             1
English             1
Computer Science    1
English Writing     1
Name: count, dtype: int64