# X = features/input columns
# y = target/answer column
# For each exercise, identify:
# Features
# Target
# Task Type
# Reason

# Exercise 1 — Student Score Prediction
# This is a regression - predicting a number

In [9]:
import pandas as pd
data = {
    "study_hours": [2,4,6,8],
    "attendance":[60,75,90,95],
    "sleep_hours":[8,7,6,5],
    "score":[45,64,85,92]
}
df=pd.DataFrame(data)
df

   study_hours  attendance  sleep_hours  score
0            2          60            8     45
1            4          75            7     64
2            6          90            6     85
3            8          95            5     92

In [10]:
X =df[["study_hours", "attendance", "sleep_hours"]]
y= df["score"]
print("Features:")
print(X)
print("Target:")
print(y)

Features:
   study_hours  attendance  sleep_hours
0            2          60            8
1            4          75            7
2            6          90            6
3            8          95            5
Target:
0    45
1    64
2    85
3    92
Name: score, dtype: int64

# Exercise 2 — House Price Prediction

In [12]:
info={
"bedrooms":[1,2,3,4],
"bathrooms":[1,2,3,4],
"house_size":[100,150,200,250],
"location_score":[32,3,4,5],
"price":[5000,7500,9000,11500]
}
df=pd.DataFrame(info)
df

   bedrooms  bathrooms  house_size  location_score  price
0         1          1         100              32   5000
1         2          2         150               3   7500
2         3          3         200               4   9000
3         4          4         250               5  11500

In [14]:
X =df[["bedrooms", "bathrooms", "house_size", "location_score"]]
y=df["price"]
print("Features:")
print(X)
print("Target:")
print(y)

Features:
   bedrooms  bathrooms  house_size  location_score
0         1          1         100              32
1         2          2         150               3
2         3          3         200               4
3         4          4         250               5
Target:
0     5000
1     7500
2     9000
3    11500
Name: price, dtype: int64

# Exercise 3 — Pass or Fail Prediction
# This is classification = prediction of category

In [15]:
class_info={
"study_hours": [2,4,6,8],
"attendance":[60,75,90,95],
"assignment_score": [45,64,85,92],
"result":["fail", "pass", "pass", "pass"]
}
df=pd.DataFrame(class_info)
df

   study_hours  attendance  assignment_score result
0            2          60                45   fail
1            4          75                64   pass
2            6          90                85   pass
3            8          95                92   pass

In [16]:
X = df[["study_hours", "attendance", "assignment_score"]]
y=df["result"]
print("Features:")
print(X)
print("Targer:")
print(y)

Features:
   study_hours  attendance  assignment_score
0            2          60                45
1            4          75                64
2            6          90                85
3            8          95                92
Targer:
0    fail
1    pass
2    pass
3    pass
Name: result, dtype: str