In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("student_classes.csv")

In [4]:
df

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [8]:
df['Student'].value_counts().sum()  #How many total students do I have?

np.int64(8)

In [12]:
df['Subject'].nunique() #How many subjects do I teach?

5

In [18]:
df['Subject'].value_counts().idxmax() #Which subject appears the most?

'Mathematics'

In [30]:
total_fee = df['Fee_GBP'].sum()  #What is my total expected fee?

In [20]:
df['Fee_GBP'].mean()  #What is my average fee per class?

np.float64(19.875)

In [21]:
df['Fee_GBP'].max() #Which students pay the highest fee?

np.int64(22)

In [25]:
df[df['Fee_GBP'] == df['Fee_GBP'].max()]['Student']

1     Taslim
5    Giselle
Name: Student, dtype: str

In [27]:
df=pd.read_csv("student_classes.csv")

In [28]:
df

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [29]:
df['Class_Day'].value_counts().idxmax() #Which day has the most classes?

'Tuesday'

In [31]:
print(f"My total expected class fee is £{total_fee}.")

My total expected class fee is £159.