In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("student_classes.csv")

In [3]:
df

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [4]:
df["Student"]

0      Amira
1     Taslim
2       Ines
3    Ainsley
4      Jason
5    Giselle
6      Karis
7     Damien
Name: Student, dtype: str

In [6]:
df[['Student', 'Subject', 'Fee_GBP']]

   Student           Subject  Fee_GBP
0    Amira       Mathematics       20
1   Taslim       Mathematics       22
2     Ines           Science       18
3  Ainsley           English       20
4    Jason       Mathematics       19
5  Giselle  Computer Science       22
6    Karis       Mathematics       20
7   Damien   English Writing       18

In [7]:
df[df['Subject']== 'Mathematics'] #Show only students taking Mathematics.

  Student      Subject Class_Day Class_Time  Duration_Minutes  Fee_GBP
0   Amira  Mathematics    Monday    4:00 PM                60       20
1  Taslim  Mathematics   Tuesday    6:00 PM                60       22
4   Jason  Mathematics  Saturday    2:00 PM                45       19
6   Karis  Mathematics    Sunday    3:00 PM                60       20

In [13]:
df[df['Fee_GBP']>=20] #Show only students whose Fee_GBP is greater than 20.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20

In [15]:
df[df['Duration_Minutes'] == 60] #Show only students whose lesson duration is exactly 60 minutes.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [20]:
df.sort_values('Fee_GBP', ascending=False)  #Sort the table by Fee_GBP from highest to lowest.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
0    Amira       Mathematics     Monday    4:00 PM                60       20
6    Karis       Mathematics     Sunday    3:00 PM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
2     Ines           Science     Friday   12:00 PM                45       18
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [21]:
df.sort_values('Student') #Sort the table by Student name alphabetically.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
3  Ainsley           English  Wednesday   10:00 AM                60       20
0    Amira       Mathematics     Monday    4:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
4    Jason       Mathematics   Saturday    2:00 PM                45       19
6    Karis       Mathematics     Sunday    3:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22

In [22]:
df.value_counts('Student') #Use .value_counts() to count how many students are taking each subject.

Student
Amira      1
Taslim     1
Ines       1
Ainsley    1
Jason      1
Giselle    1
Karis      1
Damien     1
Name: count, dtype: int64

In [25]:
df[df['Class_Day'] =='Tuesday'] #Show only students who have class on Tuesday.

  Student          Subject Class_Day Class_Time  Duration_Minutes  Fee_GBP
1  Taslim      Mathematics   Tuesday    6:00 PM                60       22
7  Damien  English Writing   Tuesday   11:00 AM                60       18