In [1]:
import pandas as pd
import numpy as np

## Exercise 1 - Find and count the missing values

In [2]:
data = {
    "student": ["A", "B", "C", "D", "E"],
    "study_hours": [2, np.nan, 5, 6, np.nan],
    "score": [50, 60, np.nan, 80, 90]
}

df = pd.DataFrame(data)
df

  student  study_hours  score
0       A          2.0   50.0
1       B          NaN   60.0
2       C          5.0    NaN
3       D          6.0   80.0
4       E          NaN   90.0

In [4]:
df.isnull()

   student  study_hours  score
0    False        False  False
1    False         True  False
2    False        False   True
3    False        False  False
4    False         True  False

In [5]:
df.isnull().sum()

student        0
study_hours    2
score          1
dtype: int64

## Exercise 2 - Fill with mean

In [6]:
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].mean())
df["study_hours"]

0    2.000000
1    4.333333
2    5.000000
3    6.000000
4    4.333333
Name: study_hours, dtype: float64

In [8]:
df["score"]=df["score"].fillna(df["score"].mean())
df["score"]

0    50.0
1    60.0
2    70.0
3    80.0
4    90.0
Name: score, dtype: float64

In [9]:
df

  student  study_hours  score
0       A     2.000000   50.0
1       B     4.333333   60.0
2       C     5.000000   70.0
3       D     6.000000   80.0
4       E     4.333333   90.0

In [10]:
df.isnull().sum()

student        0
study_hours    0
score          0
dtype: int64

## Exercise 3 - Learn with Median

In [11]:
data = {
    "income": [20000, 22000, 23000, 25000, 200000, np.nan]
}
data_income = pd.DataFrame(data)
data_income

     income
0   20000.0
1   22000.0
2   23000.0
3   25000.0
4  200000.0
5       NaN

In [15]:
data_income["income"]=data_income["income"].fillna(data_income["income"].median())
data_income["income"]

0     20000.0
1     22000.0
2     23000.0
3     25000.0
4    200000.0
5     23000.0
Name: income, dtype: float64

In [18]:
data_income["income"]=data_income["income"].fillna(data_income["income"].mean())
data_income

     income
0   20000.0
1   22000.0
2   23000.0
3   25000.0
4  200000.0
5   23000.0

## Exercise 4 - Missing text/category data

In [19]:
data = {
    "student": ["A", "B", "C", "D", "E"],
    "subject": ["Maths", "English", np.nan, "Maths", "Maths"]
}

subject_df = pd.DataFrame(data)
subject_df

  student  subject
0       A    Maths
1       B  English
2       C      NaN
3       D    Maths
4       E    Maths

In [22]:
subject_df["subject"]= subject_df["subject"].fillna(subject_df["subject"].mode()[0])
subject_df["subject"]

0      Maths
1    English
2      Maths
3      Maths
4      Maths
Name: subject, dtype: str

## Exercise 5 - Decide: Fill or delete?

In [23]:
data = {
    "student": ["A", "B", "C", "D", "E"],
    "attendance": [90, np.nan, 75, np.nan, 88],
    "score": [80, 70, np.nan, 65, 85]
}

practice_df = pd.DataFrame(data)
practice_df

  student  attendance  score
0       A        90.0   80.0
1       B         NaN   70.0
2       C        75.0    NaN
3       D         NaN   65.0
4       E        88.0   85.0

In [25]:
practice_df.isnull().sum()

student       0
attendance    2
score         1
dtype: int64

In [28]:
remove_df=practice_df.dropna()
remove_df

  student  attendance  score
0       A        90.0   80.0
4       E        88.0   85.0

In [29]:
fill_df= practice_df.copy()
fill_df

  student  attendance  score
0       A        90.0   80.0
1       B         NaN   70.0
2       C        75.0    NaN
3       D         NaN   65.0
4       E        88.0   85.0

In [30]:
fill_df["attendance"]= fill_df["attendance"].fillna(fill_df["attendance"].mean())
fill_df

  student  attendance  score
0       A   90.000000   80.0
1       B   84.333333   70.0
2       C   75.000000    NaN
3       D   84.333333   65.0
4       E   88.000000   85.0

In [32]:
fill_df["score"] = fill_df["score"].fillna(fill_df["score"].mean())
fill_df

  student  attendance  score
0       A   90.000000   80.0
1       B   84.333333   70.0
2       C   75.000000   75.0
3       D   84.333333   65.0
4       E   88.000000   85.0