In [1]:
import pandas as pd
import numpy as np

data = {
    "student": ["A", "B", "C", "D", "E", "F"],
    "study_hours": [2, 4, np.nan, 5, 6, 7],
    "attendance": [70, 78, 82, np.nan, 91, 95],
    "subject": ["Maths", "English", "Maths", "English", np.nan, "Maths"],
    "homework_score": [50, 62, 70, 75, np.nan, 90],
    "final_score": [48, 60, 69, np.nan, 85, 92]
}

df = pd.DataFrame(data)
df

  student  study_hours  attendance  subject  homework_score  final_score
0       A          2.0        70.0    Maths            50.0         48.0
1       B          4.0        78.0  English            62.0         60.0
2       C          NaN        82.0    Maths            70.0         69.0
3       D          5.0         NaN  English            75.0          NaN
4       E          6.0        91.0      NaN             NaN         85.0
5       F          7.0        95.0    Maths            90.0         92.0

In [2]:
copy_df=df.copy()
copy_df

  student  study_hours  attendance  subject  homework_score  final_score
0       A          2.0        70.0    Maths            50.0         48.0
1       B          4.0        78.0  English            62.0         60.0
2       C          NaN        82.0    Maths            70.0         69.0
3       D          5.0         NaN  English            75.0          NaN
4       E          6.0        91.0      NaN             NaN         85.0
5       F          7.0        95.0    Maths            90.0         92.0

In [3]:
copy_df["study_hours"] = copy_df["study_hours"].fillna(copy_df["study_hours"].mean())
copy_df

  student  study_hours  attendance  subject  homework_score  final_score
0       A          2.0        70.0    Maths            50.0         48.0
1       B          4.0        78.0  English            62.0         60.0
2       C          4.8        82.0    Maths            70.0         69.0
3       D          5.0         NaN  English            75.0          NaN
4       E          6.0        91.0      NaN             NaN         85.0
5       F          7.0        95.0    Maths            90.0         92.0

In [5]:
copy_df["attendance"]=copy_df["attendance"].fillna(copy_df["attendance"].mean())
copy_df

  student  study_hours  attendance  subject  homework_score  final_score
0       A          2.0        70.0    Maths            50.0         48.0
1       B          4.0        78.0  English            62.0         60.0
2       C          4.8        82.0    Maths            70.0         69.0
3       D          5.0        83.2  English            75.0          NaN
4       E          6.0        91.0      NaN             NaN         85.0
5       F          7.0        95.0    Maths            90.0         92.0

In [6]:
copy_df["subject"] = copy_df["subject"].fillna(copy_df["subject"].mode()[0])
copy_df

  student  study_hours  attendance  subject  homework_score  final_score
0       A          2.0        70.0    Maths            50.0         48.0
1       B          4.0        78.0  English            62.0         60.0
2       C          4.8        82.0    Maths            70.0         69.0
3       D          5.0        83.2  English            75.0          NaN
4       E          6.0        91.0    Maths             NaN         85.0
5       F          7.0        95.0    Maths            90.0         92.0

In [10]:
copy_df["homework_score"] = copy_df["homework_score"].fillna(copy_df["homework_score"].median())
copy_df["homework_score"]

0    50.0
1    62.0
2    70.0
3    75.0
4    70.0
5    90.0
Name: homework_score, dtype: float64

In [9]:
copy_df["final_score"] = copy_df["final_score"].fillna(copy_df["final_score"].median())
copy_df

  student  study_hours  attendance  subject  homework_score  final_score
0       A          2.0        70.0    Maths            50.0         48.0
1       B          4.0        78.0  English            62.0         60.0
2       C          4.8        82.0    Maths            70.0         69.0
3       D          5.0        83.2  English            75.0         69.0
4       E          6.0        91.0    Maths            70.0         85.0
5       F          7.0        95.0    Maths            90.0         92.0