In [3]:
import pandas as pd
df= pd.read_csv("student_final_score_project.csv")
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [4]:
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [6]:
df.isnull().sum()

student_id              0
study_hours             0
attendance             20
homework_score         22
previous_test_score    18
tutoring_sessions       0
sleep_hours            16
final_score             0
dtype: int64

In [8]:
df["attendance"] = df["attendance"].fillna(df["attendance"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [9]:
df["homework_score"] = df["homework_score"].fillna(df["homework_score"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [10]:
df["previous_test_score"] = df["previous_test_score"].fillna(df["previous_test_score"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [11]:
df["tutoring_sessions"] =df["tutoring_sessions"].fillna(df["tutoring_sessions"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [13]:
df["sleep_hours"] = df["sleep_hours"].fillna(df["sleep_hours"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [14]:
df["final_score"] = df["final_score"].fillna(df["final_score"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [15]:
df.isnull().sum()

student_id             0
study_hours            0
attendance             0
homework_score         0
previous_test_score    0
tutoring_sessions      0
sleep_hours            0
final_score            0
dtype: int64

In [17]:
X = df[[
        "study_hours",
        "attendance",
        "homework_score",
        "previous_test_score",
        "tutoring_sessions",
        "sleep_hours"
    ]]
y = df["final_score"]

In [18]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.3,
    random_state =42
)

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
model = LinearRegression()

In [24]:
model.fit(X_train, y_train)

LinearRegression()

In [27]:
predictions = model.predict(X_test)
predictions

array([ 76.81697362,  74.2365978 ,  61.18186691,  80.63559445,
        66.44185204,  75.48341464,  58.82653822,  89.65196537,
        73.27496165,  91.0131043 ,  72.10768623,  87.76456387,
        74.95698588,  76.33837589,  82.00038189,  70.01922291,
       101.39307685,  73.97032581,  96.92266214,  74.57230718,
        82.99716601,  92.17607141,  86.39760134,  77.35921717,
        72.94754304,  69.29986939,  92.68803674,  84.06234585,
        80.07933358,  82.72141233,  73.01704385,  77.52450877,
        81.3997127 ,  60.52749158,  70.13277667,  85.56696486,
        60.82218082,  76.44322206,  82.59062802,  69.50355258,
        75.30988771,  65.01291843,  69.27087108,  87.85047473,
        76.07837413,  82.44624802,  73.89619434,  88.5811084 ,
        71.26820367,  78.49566211,  74.70627898,  87.7672255 ,
        75.40044139,  68.44958942,  63.67446738,  79.18936713,
        62.41022467,  88.93026787,  55.79596704,  64.90545187,
        71.1373493 ,  67.23555884,  78.04378667,  86.03904638,
        73.17949498,  83.40100278,  74.54852988,  69.90192646,
        97.33519632,  75.58668862,  66.88961002,  90.94821829,
        98.60711504,  73.28082669,  91.12295417,  61.43122507,
        81.52664139,  78.67501   ,  76.19447929,  72.13753979,
        84.36623365,  79.38705733,  81.87657268,  79.89191951,
        81.57949294,  66.68832379,  80.8906226 ,  88.22929688,
        72.46372101,  86.23436195,  66.54053979,  78.13425929,
        77.68415461,  79.21018468,  77.63382343,  71.8416189 ,
        69.39549545,  67.45999009,  69.14020359,  73.2775277 ,
        59.63184469,  81.3782227 ,  93.11450425,  64.87828822,
        80.89206673,  81.15766501,  76.50155881,  67.09449413,
        75.90351344,  70.78997721,  75.95117751,  59.69993261,
        91.64604332,  74.35472772,  98.02681451,  76.73921461,
        83.31202044,  95.02013405,  75.19334171,  73.79111831,
        82.76753141,  81.80790795,  77.02001271,  79.22818088,
        71.55384884,  74.95665692,  76.49092861,  87.7684636 ,
        81.65469472,  79.70395898,  83.08653765,  58.68415729,
        60.82974674,  80.35194636,  94.14220323,  82.2877785 ,
        83.49696624,  82.72745128,  78.19732134,  88.76705655,
        78.69702121,  85.00134204,  80.29766809,  74.97727548,
        92.59893634,  64.03084034,  70.92859836,  69.30232853,
        86.36250513,  70.8824787 ])

In [31]:
compare_final_score = pd.DataFrame ({
    "Actual_Score": y_test.values,
    "Predicted_Score": predictions
})
compare_final_score

     Actual_Score  Predicted_Score
0            83.4        76.816974
1            74.0        74.236598
2            62.2        61.181867
3            82.1        80.635594
4            60.2        66.441852
..            ...              ...
145          58.3        64.030840
146          72.8        70.928598
147          72.1        69.302329
148          81.5        86.362505
149          77.6        70.882479

[150 rows x 2 columns]

# It's time to evaluate with MAE and R-SQUARED

In [32]:
from sklearn.metrics import mean_absolute_error, r2_score

In [34]:
mae = mean_absolute_error(y_test, predictions)
print(mae)

4.163706663713598

In [35]:
r2 = r2_score(y_test, predictions)
print(r2)

0.7381932465759578