Student Class Report Generator

In [18]:
import pandas as pd

In [2]:
df=pd.read_csv("student_classes.csv")

In [3]:
df

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [6]:
df[df["Fee_GBP"]>=20] #Show students who pay more than 20 GBP.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20

In [8]:
 df[df["Subject"] == 'Mathematics'] #Show only Mathematics students.

  Student      Subject Class_Day Class_Time  Duration_Minutes  Fee_GBP
0   Amira  Mathematics    Monday    4:00 PM                60       20
1  Taslim  Mathematics   Tuesday    6:00 PM                60       22
4   Jason  Mathematics  Saturday    2:00 PM                45       19
6   Karis  Mathematics    Sunday    3:00 PM                60       20

In [9]:
 df[df["Duration_Minutes"] == 60] #Show students with 60-minute lessons.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [13]:
   df.sort_values('Fee_GBP', ascending=False)              #Sort students by Fee_GBP from highest to lowest.

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
3  Ainsley           English  Wednesday   10:00 AM                60       20
0    Amira       Mathematics     Monday    4:00 PM                60       20
6    Karis       Mathematics     Sunday    3:00 PM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
2     Ines           Science     Friday   12:00 PM                45       18
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [16]:
df['Subject'].value_counts() #Count how many students are taking each subject.

Subject
Mathematics         4
Science             1
English             1
Computer Science    1
English Writing     1
Name: count, dtype: int64

In [17]:
df['Fee_GBP'].sum() #Calculate the total expected class fee.

np.int64(159)