In [2]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "student":["A", "B", "C", "D", "E"],
    "study_hours":[2, 4, np.nan, 6, 5],
    "attendance":[70, np.nan, 85, 90, 88],
    "score":[50, 65, 72, np.nan, 80]
}
df= pd.DataFrame(data)
df

  student  study_hours  attendance  score
0       A          2.0        70.0   50.0
1       B          4.0         NaN   65.0
2       C          NaN        85.0   72.0
3       D          6.0        90.0    NaN
4       E          5.0        88.0   80.0

## np.nan means missing value

In [5]:
df.isnull()

   student  study_hours  attendance  score
0    False        False       False  False
1    False        False        True  False
2    False         True       False  False
3    False        False       False   True
4    False        False       False  False

In [6]:
df.isnull().sum()

student        0
study_hours    1
attendance     1
score          1
dtype: int64

In [10]:
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].mean())
df["study_hours"]

0    2.00
1    4.00
2    4.25
3    6.00
4    5.00
Name: study_hours, dtype: float64

In [12]:
df["attendance"]= df["attendance"].fillna(df["attendance"].mean())
df["attendance"]

0    70.00
1    83.25
2    85.00
3    90.00
4    88.00
Name: attendance, dtype: float64

In [14]:
df["score"] = df["score"].fillna(df["score"].mean())
df["score"]

0    50.00
1    65.00
2    72.00
3    66.75
4    80.00
Name: score, dtype: float64

### For the missing values in study_hours, attendance, and score, I found the mean and used it to fill the blank in each.

In [16]:
df

  student  study_hours  attendance  score
0       A         2.00       70.00  50.00
1       B         4.00       83.25  65.00
2       C         4.25       85.00  72.00
3       D         6.00       90.00  66.75
4       E         5.00       88.00  80.00

In [17]:
df.isnull().sum()

student        0
study_hours    0
attendance     0
score          0
dtype: int64