# Week 4 Day 3 — ML Error Practice

Today, I am practising how to understand features, target values, predictions, errors, and a simple loss function.

In [5]:
import pandas as pd
data = {
    "student": ["A", "B", "C"],
    "study_hours": [2, 4, 6],
    "attendance": [70, 80, 90],
    "actual_score": [48, 65, 82],
    "predicted_score": [50, 62, 78]
}

df = pd.DataFrame(data)
df

  student  study_hours  attendance  actual_score  predicted_score
0       A            2          70            48               50
1       B            4          80            65               62
2       C            6          90            82               78

In [8]:
df["error"] = df["actual_score"] - df["predicted_score"]
df

  student  study_hours  attendance  actual_score  predicted_score  error
0       A            2          70            48               50     -2
1       B            4          80            65               62      3
2       C            6          90            82               78      4

### Question 1: Which columns are the features?

The feature columns are `study_hours` and `attendance`.

These are the pieces of information given to the model to help it make a prediction.

### Question 2: Which column is the target?

The target column is `actual_score`.

This is the real answer the model is trying to predict.

### Question 3: What does each row represent?

Each row represents one student.

For each student, the table shows their study hours, attendance, actual score, and predicted score.

### Question 4 — Calculate each student’s prediction error
df["error"] = df["actual_score"] - df["predicted_score"]
df

### Question 5 — Which prediction was closest?

In [11]:
df["absolute_error"]= df["error"].abs()
df

,student,study_hours,attendance,actual_score,predicted_score,error,absolute_error
0,A,2,70,48,50,-2,2
1,B,4,80,65,62,3,3
2,C,6,90,82,78,4,4

In [16]:
closest_prediction = df[df["absolute_error"] == df["absolute_error"].min()]
closest_prediction

,student,study_hours,attendance,actual_score,predicted_score,error,absolute_error
0,A,2,70,48,50,-2,2

### Question 6 — Which prediction was furthest away?

In [17]:
furthest_prediction = df[df["absolute_error"] == df["absolute_error"].max()]
furthest_prediction

,student,study_hours,attendance,actual_score,predicted_score,error,absolute_error
2,C,6,90,82,78,4,4

### Question 7 — Calculate the average actual score

In [26]:
average_actual_score = df["actual_score"].mean()
print(f"The average actual score is {average_actual_score:.2f}")

The average actual score is 65.00

### Question 8 — Calculate the average predicted score

In [29]:
average_predicted_score = df["predicted_score"].mean()
print(f"The average predicted score is {average_predicted_score:.0f}")

The average predicted score is 63