In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\TAIWO\Downloads\student_classes.csv")

In [3]:
df

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [4]:
df2=pd.read_csv("student_classes.csv")

In [5]:
df2

   Student           Subject  Class_Day Class_Time  Duration_Minutes  Fee_GBP
0    Amira       Mathematics     Monday    4:00 PM                60       20
1   Taslim       Mathematics    Tuesday    6:00 PM                60       22
2     Ines           Science     Friday   12:00 PM                45       18
3  Ainsley           English  Wednesday   10:00 AM                60       20
4    Jason       Mathematics   Saturday    2:00 PM                45       19
5  Giselle  Computer Science   Thursday    5:00 PM                60       22
6    Karis       Mathematics     Sunday    3:00 PM                60       20
7   Damien   English Writing    Tuesday   11:00 AM                60       18

In [7]:
df.head(3)

  Student      Subject Class_Day Class_Time  Duration_Minutes  Fee_GBP
0   Amira  Mathematics    Monday    4:00 PM                60       20
1  Taslim  Mathematics   Tuesday    6:00 PM                60       22
2    Ines      Science    Friday   12:00 PM                45       18

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student           8 non-null      str
 1   Subject           8 non-null      str
 2   Class_Day         8 non-null      str
 3   Class_Time        8 non-null      str
 4   Duration_Minutes  8 non-null      int64
 5   Fee_GBP           8 non-null      int64
dtypes: int64(2), str(4)
memory usage: 516.0 bytes

In [9]:
df.shape

(8, 6)